server:
  port: 8443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: tiketondemo
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  application:
    name: tiketondemo
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true

jwt:
  secret: ${JWT_SECRET}
  expire-time: 604800000

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDES

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true